# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='logo',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='occupancy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='parking_notes',
            field=models.TextField(null=True),
        ),
    ]
