# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 01:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_api', '0002_auto_20181122_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coordinators',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venue',
            name='coordinators',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
