# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_api', '0003_auto_20181122_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('AP', 'APPROVED'), ('PN', 'PENDING'), ('DC', 'DECLINED'), ('CN', 'CANCELED')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='occupancy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='parking_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
