# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_api', '0004_auto_20181125_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('AP', 'APPROVED'), ('PN', 'PENDING'), ('DC', 'DECLINED'), ('CN', 'CANCELED')], default='PN', max_length=200, null=True),
        ),
    ]
