# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pv_api', '0006_auto_20181127_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='spaces',
        ),
        migrations.AddField(
            model_name='space',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pv_api.Venue'),
            preserve_default=False,
        ),
    ]
