# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 21:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pv_api', '0007_auto_20181127_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='coordinators',
            field=models.ManyToManyField(related_name='event_coordinators', to=settings.AUTH_USER_MODEL),
        ),
    ]
