# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pv_api', '0008_auto_20181127_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
