# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-08 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_api', '0012_venue_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='num_guests',
            field=models.IntegerField(default=1),
        ),
    ]
